### PR TITLE
Qsv

### PR DESCRIPTION
**Pull request by jqnatividad**

### CODE REVIEW

**Comment by peterjc** [comment]
10,000 commits? I'll just update my main branch to match upsteam and rebase this...

**Comment by peterjc** [comment]
Rebased onto my qsv branch, and pull request changed to point at that branch...

**Comment by peterjc** [comment]
I suggest I squash-and-merge this into my branch, and then I retry this as a pull request to https://github.com/conda-forge/staged-recipes

Or, you could just try making a pull request directly to https://github.com/conda-forge/staged-recipes yourself?

**Comment by jqnatividad** [comment]
Hi @peterjc ,
Do you mind running with this? I'm afraid I don't have bandwidth to ramp-up on conda-forge...

Looking at diff/commit history... we tried a lot of things to get the python feature to work...  perhaps you can reset and start with a simpler recipe without the DSO stuff and other workarounds now that we're not trying to get the python feature enabled...

Sorry - Joel

**Comment by peterjc** [comment]
See https://github.com/conda-forge/staged-recipes/pull/24081

**Pull request merged**
